= Agile Patterns: The Technical Cluster

_2009-10-20_

* Recently I have finished reading link:http://www.infoq.com/minibooks/agile-patterns[Agile Patterns: The Technical Cluster] online book provided by InfoQ. As sometimes happens, the book describes how things should be and once again you see how things actually aren't. And that is sad. I had successful experience of working in agile team on agile project, and, clearly, I can understand the benefits this book is talking about. Of course, most of us had an experience working in not so agile teams on not so agile projects and, clearly, one can understand smells book is talking about. Nothing new actually (regarding patterns and methodologies). What was very surprising, interesting and helpful is *link between patterns and business value*. This book takes very interesting approach: first focusing on how to deliver business value using this or that agile pattern as a tool.
* Once, I was criticized for caring about methodology, tests, continuous integration, sources management and so on while I should have been focusing on delivering *business value*. I had nothing to answer. Now I do know that making things easier for team does provide real *business value*. Functional, integration and unit tests, continuous integration, collective code ownership, agile process supporting evolutionary design, finally scrum are making things easier for the team. Time isn't wasted on these things instead of implementing new features. Instead, they do provide *business value*.
* Do you need specific terms to talk to your management like "_reduce time to market_", "_increase product lifetime_" or "_increase visibility_"? Then read it yourself. I wish I did it earlier.
