= Scrum practice. Part 2: Planning

_2009-03-22_

* It does not work good if there are no story cards during planning. It may seem to be enough to have just piece of paper where there are written story names and story points. But it is not. During planning team may decompose story into several tasks that may be done in parallel. Or team may identify steps that should be done sequentially to achieve goal. This information should not be lost. *Best way* to preserve it *is to have story card along with task cards*. Story card is used to group task cards and also to keep total story points needed to implement story. Product owner may use this information to reorder stories that team decided to implement during a sprint. What is also important is that during planning team may identify important high level or low level implementation details. Or team may make decision on what have to be done or not to be done in a particular task. (For example team may decide that some specific technology may be used or that there was class X that should help or that something like that was done in a module Y. Or for example team may decide that one who will take this task also should/should not implement automatic acceptance tests or update manual.) Team may write down this information on task cards. Also task cards are useful to keep track of additional information: how much story points left to complete task, who is currently doing task, who are testers for this task, who of testers are already accepted work and are ready to say "done". (There is no need to prepare these cards in advance. One person may write down on pieces of paper while others discussing.)
* *There are really should be a wall or white board* with a story and task cards, with burn-down chart, with place for next and unplanned story and task cards, with information about how many days left, with spring schedule (if team uses one) and perhaps with other important info. Single piece of paper where names of all stories is written or electronic spreadsheets don`t work good enough. Once team try wall/white board way then there is strong wish to use this approach. This is because it is much simpler to get information. It is much simpler to update information. It is much simpler to add information. Once someone thinks that work is done then he/they ask who can test, write down testers` names on task card, choose another task card that he/they can do best (remember that there are implementation notices, notices on an amount of work and number of estimated story points on task cards that are easy to read), write down own name(s) on task card and go work (perhaps first he/they take cards with his/their names as testers). Of course, it is same easy to update information during daily meetings.
* Of course team should make everything that is possible and impossible to complete all stories to achieve goals. But things happen. People may become sick. Nasty hard to fix bug may be found that must be fixed in next version. Unseen technical problem may be discovered that needs to be solved to complete task. It may be impossible to complete all stories. This is when Product owner should make decision which stories have higher priority. Problem is that it is usually too late when it becomes clear that team will not be able to complete everything. That is why it is important that team should know which stories are of higher priorities since first day of sprint. More important stories should be of higher priority. Technically difficult stories should be of higher priorities. Large stories where there is limited number of people who can participate (when tasks can not be done in parallel) should be of higher priority (so story have more chances to be completed). Usually some of team members that have done other work can help those that have tasks that other way will not be done in time. But chances are less when all hard work is left at the end. Summary: team should identify risky stories, make Product owner aware of them, Product owner should assign priorities to stories, *team should give attention to priorities when selecting task cards*. That is very important. Because most of the time it is better to have at least some of the most important stories fully complete than have all stories in progress and none complete.
* When planning and estimating story points for a task (or a story) team should take into account that task (or story) should be tested and all bugs fixed. There may be or may not be dedicated task card to test story. What is important is that team should plan time to test and fix bugs. If team does not than such activities as testing tasks and stories and immediately fixing bugs (or immediately refactoring code that smells) are assigned low priorities. Everyone preferred to "complete" more story points than less. No one want to spend time on testing task that have zero story points left. This is because she will not be "rewarded" (what? you spent two hours testing this task? there was nothing left to do). Also, it is unnatural to return estimated story points from zero to some other value if bugs were found (and some time needed to fix them). It is worse if bugs were found and story points were left at zero. Ignoring testing and bugs fixing leads to generally worse quality of product. Also it is harder to keep track of story progress. There are more chances to get "almost done" story that have discovered bugs left at end of sprint. Better approach is to *plan testing and bugs fixing*. Doing this way it is clear that task or story is only halfway from "done" when it enters a testing phase. Testers will write off story points when they are done with testing and all discovered bugs are fixed. Team (together with Product owner) will get more realistic estimate. Team (together with Product owner) will see where story points were spent and how much must be spent to actually have story really done. This have two consequences. First is that team actually see what have to be done and when (most of time it is better to fix bugs from "almost done" an important story than spend time on next one), team members have legal reason to spend time on testing. Second consequence is that product will be of higher quality (it will be tested better, there will be more bugs fixed earlier). Most of the time that means that clients will be more satisfied (sure nobody likes buggy software).
* There are several methods to making decisions what stories will be taken during next sprint. One is planning poker. For each task team member secretly select one card with predefined number of story points. Then all cards are opened and average is taken as estimated story points for that task (if dispersion is not too high). What is important is that there are finite number of cards and their number usually is not high. Often these numbers are like: 1, 2, 5, 10, 20, 40, 100 (Scrum from the trenches). Some teams may see story point as ideal main-hour, other as ideal man-day. Let's imagine that man-hours are used and I think that current task will take like 30 man-hours (actually 3 days). What card i should choose? 20 or 40? If i choose 20 then there will be greater chances that I will not be able to finish task at time. If I choose 40 then task will be overestimated. Focus factor will grow without additional functionality being delivered to user. It is ok if such a situation happens rarely. *But something really should be changed if Scrum masters hears "i have no such card" several times every planning*. It is not excuse that such numbers are written somewhere. Scrum is agile methodology. If something impede then  it should be removed. If cards for planning poker doesn't suit team then they should be changed. Remember: Scrum is about being agile. If team members need 3, 8, 16, 25, 40 most of time then such numbers should be written on cards for planning poker. One will have less time thinking when choosing from two cards - faster planning. Tasks and stories will be estimated more accurately - will be easier to track progress (because of less overestimation) and fewer chances to not deliver functionality that was promised to be delivered (because of underestimation).
* *Use cases should really be done in a previous sprint*. Sometimes there may be no use cases at all. Sometimes use cases are fast written day before planning. Sometimes use cases are written day after planning. That does not work good. Team needs to see what actually have to be done to be able to give a realistic estimate. If team produce implementation notes for draft use cases during planning discussion then it is likely waste of time. Because use cases are likely to change because of defects discovered during implementation. This slows team down. New unseen (due to low quality of use cases or their absence) technical problems may be discovered. It is harder for one man (if pair programming isn't used) to find solution (in contrast with discussion during planning). When there are no use cases (or other specification, or they are of poor quality) it is likely that there will not be implemented something Product owner expects to see (or will be implemented something Product owner did not expect to see). There is high risk of poor quality use cases to be changed several times per day because of defects discovered during implementation or testing. It is more time and effort efficient to produce high quality use cases in advance. So team discover all implementation difficulties during planning. Implementor should see full story scope from use cases and don't have to reimplement feature several times during sprint.
* Generally, I think that *it isn't too bad to spend some time planning* (say whole day). If team collectively discusses stories, decomposes them and identifies tasks, finds ways to implement things then it will be easier for individual team members to complete individual tasks. Each individual team member will not have to solve difficult complex problem alone. He will use solutions found by "hive mind" during planning. This lowers risks and increases productivity.
